files:
  bid_data_test: bid_requests_test.csv
  bid_data_train: bid_requests_train.csv
  click_data_train: click_data_train.csv
  click_data_test: click_data_test.csv
  page_data: page_data.csv
  user_data: user_data.csv
model_params:
  max_features: 1000
  max_iter: 1000
  page_clusters: 7
  seed: 42
  user_clusters: 5
paths:
  data_dir: ./
  models_dir: ./models/
training:
  test_split: 0.2
  threshold: 0.5
